language: node_js
node_js:
  - "8"

install: "echo 'This is static content - nothing to install!'"
script:
  - mkdir build
  - mv images build
  - mv style.css build

deploy:
  provider: s3
  bucket: content.demo.microfrontends.com
  local_dir: build
  skip_cleanup: true

after_deploy:
  - >
      DISTRIBUTION_ID=`
      aws cloudfront list-distributions |
      jq --raw-output '
      .DistributionList.Items[] |
      select(.Aliases.Items[0] == "content.demo.microfrontends.com") |
      .Id
      '`
  - "echo invalidating $DISTRIBUTION_ID"
  - "aws cloudfront create-invalidation $DISTRIBUTION_ID"
